export enum MedicineCategory {
  Analgesics = 'Analgesics',
  Antibiotics = 'Antibiotics',
  Antidepressants = 'Antidepressants',
  Antihistamines = 'Antihistamines',
  CardiovascularMedications = 'Cardiovascular medications',
  EndocrineMedications = 'Endocrine medications',
  RespiratoryMedications = 'Respiratory medications',
  MuscleRelaxants = 'Muscle relaxants',
  AntiInflammatoryDrugs = 'Anti-inflammatory drugs',
  Immunosuppressants = 'Immunosuppressants',
  Anesthetics = 'Anesthetics',
  Antacids = 'Antacids',
  Anticoagulants = 'Anticoagulants',
  Anticonvulsants = 'Anticonvulsants',
  Antiemetics = 'Antiemetics',
  AntifungalMedications = 'Antifungal medications',
  AntimalarialDrugs = 'Antimalarial drugs',
  Antipsychotics = 'Antipsychotics',
  AntiviralMedications = 'Antiviral medications',
  ChemotherapyDrugs = 'Chemotherapy drugs',
}
