export enum MedicineCategory {
  Analgesics = 'Analgesics',
  Antibiotics = 'Antibiotics',
  Antidepressants = 'Antidepressants',
  Antihistamines = 'Antihistamines',
  CardiovascularMedications = 'Cardiovascular medications',
  EndocrineMedications = 'Endocrine medications',
  RespiratoryMedications = 'Respiratory medications',
  MuscleRelaxants = 'Muscle relaxants',
  AntiInflammatoryDrugs = 'Anti-inflammatory drugs',
  Immunosuppressants = 'Immunosuppressants',
  Anesthetics = 'Anesthetics',
  Antacids = 'Antacids',
  Anticoagulants = 'Anticoagulants',
  Anticonvulsants = 'Anticonvulsants',
  Antiemetics = 'Antiemetics',
  AntifungalMedications = 'Antifungal medications',
  AntimalarialDrugs = 'Antimalarial drugs',
  Antipsychotics = 'Antipsychotics',
  AntiviralMedications = 'Antiviral medications',
  ChemotherapyDrugs = 'Chemotherapy drugs',
}

export enum MedicalSpecialties {
  AllergyAndImmunology = 'Allergy and Immunology',
  Anesthesiology = 'Anesthesiology',
  Cardiology = 'Cardiology',
  Dermatology = 'Dermatology',
  EmergencyMedicine = 'Emergency Medicine',
  Endocrinology = 'Endocrinology',
  FamilyMedicine = 'Family Medicine',
  Gastroenterology = 'Gastroenterology',
  Geriatrics = 'Geriatrics',
  Hematology = 'Hematology',
  InfectiousDisease = 'Infectious Disease',
  InternalMedicine = 'Internal Medicine',
  MedicalGenetics = 'Medical Genetics',
  Neurology = 'Neurology',
  NuclearMedicine = 'Nuclear Medicine',
  ObstetricsAndGynecology = 'Obstetrics and Gynecology',
  Oncology = 'Oncology',
  Ophthalmology = 'Ophthalmology',
  OrthopedicSurgery = 'Orthopedic Surgery',
  Otolaryngology = 'Otolaryngology',
  Pathology = 'Pathology',
  Pediatrics = 'Pediatrics',
  PhysicalMedicineAndRehabilitation = 'Physical Medicine and Rehabilitation',
  PlasticSurgery = 'Plastic Surgery',
  PreventiveMedicine = 'Preventive Medicine',
  Psychiatry = 'Psychiatry',
  Pulmonology = 'Pulmonology',
  Radiology = 'Radiology',
  Rheumatology = 'Rheumatology',
  SportsMedicine = 'Sports Medicine',
  ThoracicSurgery = 'Thoracic Surgery',
  Urology = 'Urology',
}

export enum DrugArray {
  Acetaminophen = 'Acetaminophen',
  Ibuprofen = 'Ibuprofen',
  Aspirin = 'Aspirin',
  Amoxicillin = 'Amoxicillin',
  Ciprofloxacin = 'Ciprofloxacin',
  Fluoxetine = 'Fluoxetine',
  Sertraline = 'Sertraline',
  Lisinopril = 'Lisinopril',
  Losartan = 'Losartan',
  Metformin = 'Metformin',
  Lansoprazole = 'Lansoprazole',
  Omeprazole = 'Omeprazole',
  Atorvastatin = 'Atorvastatin',
  Simvastatin = 'Simvastatin',
  Furosemide = 'Furosemide',
  Levothyroxine = 'Levothyroxine',
  Albuterol = 'Albuterol',
  Montelukast = 'Montelukast',
  Ranitidine = 'Ranitidine',
  Promethazine = 'Promethazine',
}

export enum BrandArray {
  Pfizer = 'Pfizer',
  Novartis = 'Novartis',
  Roche = 'Roche',
  MerckAndCo = 'Merck & Co.',
  JohnsonAndJohnson = 'Johnson & Johnson',
  Bayer = 'Bayer',
  Sanofi = 'Sanofi',
  GlaxoSmithKline = 'GlaxoSmithKline',
  AstraZeneca = 'AstraZeneca',
  EliLilly = 'EliLilly',
}

export enum DosageArray {
  TwoAndHalfMg = '2.5 mg',
  FiveMg = '5 mg',
  TenMg = '10 mg',
  TwentyMg = '20 mg',
  TwentyFiveMg = '25 mg',
  FiftyMg = '50 mg',
  SeventyFiveMg = '75 mg',
  OneHundredMg = '100 mg',
  OneHundredTwentyFiveMg = '125 mg',
  OneHundredFiftyMg = '150 mg',
  TwoHundredMg = '200 mg',
  TwoHundredFiftyMg = '250 mg',
  ThreeHundredMg = '300 mg',
  FourHundredMg = '400 mg',
  FiveHundredMg = '500 mg',
  SixHundredMg = '600 mg',
  EightHundredMg = '800 mg',
  OneG = '1 g',
  TwoG = '2 g',
}

export enum FrequencyArray {
  Example1 = 'Exampl 1',
  Example2 = 'Exampl 2',
  Example3 = 'Exampl 3',
  Example4 = 'Exampl 4',
  Example5 = 'Exampl 5',
}
